# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=journeymapfogofwar
# your properties
curse_slug=_curseslug_
curse_id=0
mod_version=0.0.2-SNAPSHOT

neo_version=47.1.106

mod_name=JourneyMap: Fog of War
mod_group_id=com.lothrazar.examplemod

mod_license=SeeGithub
mod_authors=polygeist111
mod_name=JourneyMap: Fog of War
mod_description=Adds a networked fog of war overlay for journeymap on pregenerated worlds
neo_version_range=[47.1,)
loader_version_range=[47,)
mapping_channel=official
minecraft_version=1.20.1
mc_version=1.20.1


flib_version=0.0.14
flib_file=5495793

patchouli_version=84
jei_version=15.3.0.4
curios_version=5.7.2
crafttweaker_version=14.0.38

#group=info.journeymap
#archivesBaseName=journeymap-api
#api_version=1.9-SNAPSHOT
journeymap_api_version=1.20-1.9-SNAPSHOT
jm_project_id=32274
jm_file_id=3573567
#32274
#3573567
#3587042